import React, { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Paperclip,
  RefreshCw,
  RotateCcw,
  Search,
  Star,
  Trash2,
} from "lucide-react";

import "./Trash.css";

/* =========================================================
   TYPES
   ========================================================= */

interface TrashMail {
  id: number;
  sender: string;
  email: string;
  subject: string;
  preview: string;
  date: string;
  time: string;
  starred?: boolean;
  attachment?: boolean;
}

/* =========================================================
   DEMO DATA
   ========================================================= */

const initialTrashMails: TrashMail[] = [
  {
    id: 1,
    sender: "Fleet Operations",
    email: "operations@abnfleet.com",
    subject: "Old Fleet Report",
    preview: "Previous fleet operation report that is no longer required.",
    date: "22 Aug",
    time: "17:40",
    attachment: true,
  },

  {
    id: 2,
    sender: "ABN Helpdesk",
    email: "helpdesk@abnfleet.com",
    subject: "Resolved Ticket #ABN-1021",
    preview:
      "This ticket has been resolved and the conversation is no longer active.",
    date: "21 Aug",
    time: "13:22",
    starred: true,
  },

  {
    id: 3,
    sender: "System",
    email: "system@abnfleet.com",
    subject: "System Notification",
    preview: "This notification was automatically generated by the system.",
    date: "20 Aug",
    time: "09:18",
  },

  {
    id: 4,
    sender: "SAP Integration",
    email: "sap@abnfleet.com",
    subject: "Synchronization Result",
    preview: "Previous SAP synchronization information and processing result.",
    date: "19 Aug",
    time: "18:05",
    attachment: true,
  },

  {
    id: 5,
    sender: "Fleet Manager",
    email: "fleet.manager@abnfleet.com",
    subject: "Old Weekly Summary",
    preview: "Archived weekly fleet performance summary.",
    date: "18 Aug",
    time: "11:30",
  },
];

/* =========================================================
   CONSTANTS
   ========================================================= */

const MAILS_PER_PAGE = 6;

/* =========================================================
   COMPONENT
   ========================================================= */

const Trash: React.FC = () => {
  const [mails, setMails] = useState<TrashMail[]>(initialTrashMails);

  const [search, setSearch] = useState("");

  const [selectedIds, setSelectedIds] = useState<number[]>([]);

  const [page, setPage] = useState(1);

  /* =======================================================
     FILTER
     ======================================================= */

  const filteredMails = useMemo(() => {
    const keyword = search.trim().toLowerCase();

    if (!keyword) {
      return mails;
    }

    return mails.filter(
      (mail) =>
        mail.sender.toLowerCase().includes(keyword) ||
        mail.email.toLowerCase().includes(keyword) ||
        mail.subject.toLowerCase().includes(keyword) ||
        mail.preview.toLowerCase().includes(keyword),
    );
  }, [mails, search]);

  /* =======================================================
     PAGINATION
     ======================================================= */

  const totalPages = Math.max(
    1,
    Math.ceil(filteredMails.length / MAILS_PER_PAGE),
  );

  /*
   * Prevent invalid page after deleting items.
   */

  useEffect(() => {
    if (page > totalPages) {
      setPage(totalPages);
    }
  }, [page, totalPages]);

  const visibleMails = filteredMails.slice(
    (page - 1) * MAILS_PER_PAGE,
    page * MAILS_PER_PAGE,
  );

  /* =======================================================
     SELECTION
     ======================================================= */

  const allVisibleSelected =
    visibleMails.length > 0 &&
    visibleMails.every((mail) => selectedIds.includes(mail.id));

  const toggleSelect = (id: number) => {
    setSelectedIds((current) =>
      current.includes(id)
        ? current.filter((item) => item !== id)
        : [...current, id],
    );
  };

  const toggleSelectAll = () => {
    if (allVisibleSelected) {
      setSelectedIds((current) =>
        current.filter((id) => !visibleMails.some((mail) => mail.id === id)),
      );

      return;
    }

    setSelectedIds((current) => [
      ...new Set([...current, ...visibleMails.map((mail) => mail.id)]),
    ]);
  };

  /* =======================================================
     REFRESH
     ======================================================= */

  const handleRefresh = () => {
    /*
     * Backend/API integration will be connected here.
     *
     * Example later:
     * GET /api/mail/trash
     */

    setPage(1);
    setSelectedIds([]);
  };

  /* =======================================================
     RESTORE SELECTED
     ======================================================= */

  const restoreSelected = () => {
    if (selectedIds.length === 0) {
      return;
    }

    /*
     * Later:
     * POST /api/mail/restore
     *
     * Current demo behavior:
     * remove from Trash.
     */

    setMails((current) =>
      current.filter((mail) => !selectedIds.includes(mail.id)),
    );

    setSelectedIds([]);
  };

  /* =======================================================
     DELETE SELECTED PERMANENTLY
     ======================================================= */

  const deleteSelectedPermanently = () => {
    if (selectedIds.length === 0) {
      return;
    }

    const confirmed = window.confirm(
      `Delete ${selectedIds.length} selected message${
        selectedIds.length > 1 ? "s" : ""
      } permanently?`,
    );

    if (!confirmed) {
      return;
    }

    /*
     * Later:
     * DELETE /api/mail/permanent
     */

    setMails((current) =>
      current.filter((mail) => !selectedIds.includes(mail.id)),
    );

    setSelectedIds([]);
  };

  /* =======================================================
     RESTORE SINGLE
     ======================================================= */

  const restoreMail = (id: number) => {
    /*
     * Later:
     * POST /api/mail/:id/restore
     */

    setMails((current) => current.filter((mail) => mail.id !== id));

    setSelectedIds((current) => current.filter((item) => item !== id));
  };

  /* =======================================================
     DELETE SINGLE PERMANENTLY
     ======================================================= */

  const deleteMailPermanently = (id: number) => {
    const confirmed = window.confirm("Delete this message permanently?");

    if (!confirmed) {
      return;
    }

    /*
     * Later:
     * DELETE /api/mail/:id/permanent
     */

    setMails((current) => current.filter((mail) => mail.id !== id));

    setSelectedIds((current) => current.filter((item) => item !== id));
  };

  /* =======================================================
     STAR
     ======================================================= */

  const toggleStar = (id: number) => {
    setMails((current) =>
      current.map((mail) =>
        mail.id === id
          ? {
              ...mail,
              starred: !mail.starred,
            }
          : mail,
      ),
    );
  };

  /* =======================================================
     OPEN MAIL
     ======================================================= */

  const openMail = (id: number) => {
    /*
     * Later:
     * navigate(`/mail/trash/${id}`)
     */

    console.log("Open deleted mail:", id);
  };

  /* =======================================================
     RENDER
     ======================================================= */

  return (
    <div className="trash-page">
      {/* ===================================================
          HEADER
          =================================================== */}

      <div className="trash-header">
        <div>
          <div className="trash-title-row">
            <Trash2 size={22} strokeWidth={2} />

            <h1>Trash</h1>

            {mails.length > 0 && (
              <span className="trash-count">{mails.length}</span>
            )}
          </div>

          <p>Deleted messages are kept here until permanently removed.</p>
        </div>
      </div>

      {/* ===================================================
          WARNING
          =================================================== */}

      <div className="trash-warning">
        <AlertTriangle size={17} />

        <span>
          Messages permanently deleted from Trash cannot be recovered.
        </span>
      </div>

      {/* ===================================================
          CARD
          =================================================== */}

      <section className="trash-card">
        {/* =================================================
            TOOLBAR
            ================================================= */}

        <div className="trash-toolbar">
          <div className="trash-toolbar-left">
            <label className="trash-checkbox" title="Select all">
              <input
                type="checkbox"
                checked={allVisibleSelected}
                onChange={toggleSelectAll}
              />

              <span />
            </label>

            <button
              type="button"
              className="trash-tool-button"
              onClick={handleRefresh}
              title="Refresh"
            >
              <RefreshCw size={17} />
            </button>

            {selectedIds.length > 0 && (
              <>
                <button
                  type="button"
                  className="trash-tool-button restore"
                  onClick={restoreSelected}
                  title="Restore selected"
                >
                  <RotateCcw size={17} />
                </button>

                <button
                  type="button"
                  className="trash-tool-button danger"
                  onClick={deleteSelectedPermanently}
                  title="Delete permanently"
                >
                  <Trash2 size={17} />
                </button>
              </>
            )}
          </div>

          {/* SEARCH */}

          <div className="trash-search">
            <Search size={17} />

            <input
              type="text"
              value={search}
              onChange={(event) => {
                setSearch(event.target.value);
                setPage(1);
              }}
              placeholder="Search trash..."
              aria-label="Search trash"
            />
          </div>
        </div>

        {/* =================================================
            LIST
            ================================================= */}

        <div className="trash-list">
          {visibleMails.length === 0 ? (
            <div className="trash-empty">
              <Trash2 size={42} />

              <h3>Trash is empty</h3>

              <p>There are no deleted messages matching your search.</p>
            </div>
          ) : (
            visibleMails.map((mail) => (
              <div
                key={mail.id}
                className="trash-message"
                onClick={() => openMail(mail.id)}
              >
                {/* CHECKBOX */}

                <label
                  className="trash-checkbox"
                  onClick={(event) => event.stopPropagation()}
                >
                  <input
                    type="checkbox"
                    checked={selectedIds.includes(mail.id)}
                    onChange={() => toggleSelect(mail.id)}
                  />

                  <span />
                </label>

                {/* STAR */}

                <button
                  type="button"
                  className={`trash-star ${mail.starred ? "active" : ""}`}
                  onClick={(event) => {
                    event.stopPropagation();
                    toggleStar(mail.id);
                  }}
                  title={mail.starred ? "Unstar" : "Star"}
                  aria-label={mail.starred ? "Unstar" : "Star"}
                >
                  <Star
                    size={17}
                    fill={mail.starred ? "currentColor" : "none"}
                  />
                </button>

                {/* SENDER */}

                <div className="trash-sender" title={mail.email}>
                  <span>{mail.sender}</span>
                </div>

                {/* CONTENT */}

                <div className="trash-content" title={mail.preview}>
                  <strong>{mail.subject}</strong>

                  <span> — {mail.preview}</span>
                </div>

                {/* ATTACHMENT */}

                {mail.attachment && (
                  <Paperclip className="trash-attachment" size={16} />
                )}

                {/* DATE */}

                <div className="trash-date">
                  <span>{mail.date}</span>

                  <small>{mail.time}</small>
                </div>

                {/* RESTORE */}

                <button
                  type="button"
                  className="trash-restore"
                  onClick={(event) => {
                    event.stopPropagation();
                    restoreMail(mail.id);
                  }}
                  title="Restore"
                  aria-label="Restore"
                >
                  <RotateCcw size={16} />
                </button>

                {/* MORE */}

                <button
                  type="button"
                  className="trash-more"
                  onClick={(event) => event.stopPropagation()}
                  title="More"
                  aria-label="More"
                >
                  <MoreHorizontal size={18} />
                </button>

                {/* DELETE */}

                <button
                  type="button"
                  className="trash-delete"
                  onClick={(event) => {
                    event.stopPropagation();

                    deleteMailPermanently(mail.id);
                  }}
                  title="Delete permanently"
                  aria-label="Delete permanently"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))
          )}
        </div>

        {/* =================================================
            FOOTER
            ================================================= */}

        <div className="trash-footer">
          <span>
            {filteredMails.length === 0
              ? "0 messages"
              : `${(page - 1) * MAILS_PER_PAGE + 1}–${Math.min(
                  page * MAILS_PER_PAGE,
                  filteredMails.length,
                )} of ${filteredMails.length}`}
          </span>

          <div className="trash-pagination">
            <button
              type="button"
              disabled={page <= 1}
              onClick={() => setPage((current) => Math.max(1, current - 1))}
              title="Previous page"
              aria-label="Previous page"
            >
              <ChevronLeft size={17} />
            </button>

            <span>
              {page} / {totalPages}
            </span>

            <button
              type="button"
              disabled={page >= totalPages}
              onClick={() =>
                setPage((current) => Math.min(totalPages, current + 1))
              }
              title="Next page"
              aria-label="Next page"
            >
              <ChevronRight size={17} />
            </button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Trash;
